# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayPriceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail_url', models.CharField(max_length=1924)),
                ('min_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('max_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('area', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'baojia_feijiu',
            },
        ),
    ]
