# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeijiuWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daypriceinfo',
            name='detail_url',
            field=models.CharField(max_length=1024),
        ),
    ]
